# Generated by Django 3.2.7 on 2021-10-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='api_main.Publication')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
