# Generated by Django 3.2.7 on 2021-10-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0008_auto_20211004_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mso',
            name='HQ',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='api_main.hq'),
        ),
        migrations.AlterField(
            model_name='mso',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
