# Generated by Django 3.2.7 on 2021-10-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0010_auto_20211004_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='chemist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mso',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='arc',
            old_name='Business Type',
            new_name='business_type',
        ),
        migrations.RenameField(
            model_name='arc',
            old_name='Person in Charge',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='arc',
            old_name='Retailer Name',
            new_name='person_in_charge',
        ),
        migrations.RenameField(
            model_name='arc',
            old_name='Products Under Support',
            new_name='products_under_support',
        ),
        migrations.RenameField(
            model_name='arc',
            old_name='Select Sitting Doctor',
            new_name='sitting_doctor_id',
        ),
        migrations.RenameField(
            model_name='chemist',
            old_name='Business Type',
            new_name='business_type',
        ),
        migrations.RenameField(
            model_name='chemist',
            old_name='Chemist Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='chemist',
            old_name='Person in Charge',
            new_name='person_in_charge',
        ),
        migrations.RenameField(
            model_name='chemist',
            old_name='Products Under Support',
            new_name='products_under_support',
        ),
        migrations.RenameField(
            model_name='chemist',
            old_name='Select Sitting Doctor',
            new_name='sitting_doctor_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Support Category',
            new_name='support_category',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='mso',
            old_name='Connected ARCs',
            new_name='connected_arc',
        ),
        migrations.RenameField(
            model_name='mso',
            old_name='Connected Chemists',
            new_name='connected_chemists',
        ),
        migrations.RenameField(
            model_name='mso',
            old_name='Connected Doctors',
            new_name='connected_doctors',
        ),
        migrations.RenameField(
            model_name='mso',
            old_name='HQ',
            new_name='hq',
        ),
        migrations.RenameField(
            model_name='mso',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mso',
            old_name='Territory',
            new_name='territory',
        ),
    ]
