# Generated by Django 3.2.7 on 2021-10-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0011_auto_20211004_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBLR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('date', models.DateField()),
                ('mso', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='api_main.mso')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
