# Generated by Django 3.2.7 on 2021-10-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0012_sblr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sblr',
            options={'ordering': ['mso']},
        ),
    ]
