# Generated by Django 3.2.7 on 2021-10-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0013_alter_sblr_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('person_in_charge', models.CharField(max_length=255)),
                ('stockist_type', models.CharField(choices=[('ALLOPATH', 'Allopath'), ('ABSOLUTE_AYURVEDA', 'Absolute Ayurveda'), ('GENERALS', 'Generals')], max_length=255)),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('BOTH', 'Both')], max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
