# Generated by Django 3.2.7 on 2021-10-07 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_main', '0016_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=10101, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_main.mso'),
        ),
    ]
