# Generated by Django 3.2.7 on 2021-10-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0017_auto_20211007_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
