# Generated by Django 3.2.7 on 2022-01-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0018_auto_20211007_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pop',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['name']},
        ),
    ]
