# Generated by Django 3.2.7 on 2022-02-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_main', '0019_auto_20220126_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='connected_stockists',
            field=models.ManyToManyField(to='api_main.Stockist'),
        ),
    ]
