# Generated by Django 3.2.7 on 2021-10-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_auto_20211004_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['Retailer Name']},
        ),
        migrations.AlterModelOptions(
            name='chemist',
            options={'ordering': ['Chemist Name']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='hq',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mso',
            options={'ordering': ['Name']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='Type',
            field=models.CharField(choices=[('P', 'Prescriber'), ('D', 'Dispenser'), ('B', 'Both')], default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Degree',
            field=models.CharField(max_length=255),
        ),
    ]
